import Head from "next/head";
import LandingPage from "./home/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sitanshu Mustafi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <main>
        <LandingPage />
      </main>
    </div>
  );
}
